# .scrutinizer.yml

build:

    dependencies:
        before:
            - rm composer.lock

    tests:
        override:
            -
                command: 'vendor/bin/phpunit'
                coverage:
                    file: 'coverage'
                    format: 'php-clover'


    nodes:
        php73:
            environment:
                php: 7.3

        php74:
            environment:
                php: 7.4

        php80:
            environment:
                php: 8.0

        php81:
            environment:
                php: 8.1


checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - tests/*



